spring:
  application:
    name: InnowisePaymentService

  data:
    mongodb:
      uri: ${MONGO_URI}

  liquibase:
    enabled: false

app:
  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml
    url: ${spring.data.mongodb.uri}

services:
  api-gateway:
    url: ${GATEWAY_URL}

logging:
  level:
    liquibase: DEBUG
    org.springframework.boot.autoconfigure.liquibase: DEBUG
