spring:
  application:
    name: InnowisePaymentService

  data:
    mongodb:
      uri: ${MONGO_URI}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'

app:
  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml
    url: ${MONGO_URI}
  kafka:
    topic:
      create-order: ${KAFKA_TOPIC_CREATE_ORDER}
      create-payment: ${KAFKA_TOPIC_CREATE_PAYMENT}

services:
  api-gateway:
    url: ${GATEWAY_URL}
  random-number-api:
    path: ${RANDOM_NUMBER_API_PATH}

logging:
  level:
    liquibase: DEBUG
    org.springframework.boot.autoconfigure.liquibase: DEBUG

server:
  port: ${SERVER_PORT:8083}